Initial service.
windbreaker-io/windbreaker-badges pull request #1
Opened 2017-09-12 21:32 UTC by austinkelleher

This initial PR exposes an HTTP endpoint that will serve always serve a "Windbreaker Enabled" SVG badge.

`http://localhost:8080/:owner/:repo,svg` => `http://localhost:8080/windbreaker-io/windbreaker-badges.svg`

2017-09-12 23:39 UTC, Druotic requested changes

2017-09-12 23:39 UTC, Druotic commented on package.json
> +  "name": "windbreaker-hooks",
ORLY?

2017-09-12 23:39 UTC, Druotic commented on .travis.yml
> +    secure: MFbeaRP3DIUiUtPxmPR/jAofx5XdLxs1OnNBiu48u+i/G0jsLD69p9UCuQoo1Z8y83hS8+rXK/khi00IDK3yZlpfpv8RwaQ5O3bcIw7yie0K6LT7Dy0eGMHqXwM/bivPMfqzhlHOaN190iWRCZvCmGnRiJW8jpSowxjTK15VlBfiyfEpsOfNclpZ1D5
Isn't this just copied from hooks?

2017-09-12 23:39 UTC, Druotic commented on Dockerfile
> +ENV HOME=/usr/windbreaker-hooks
hooks

2017-09-12 23:39 UTC, Druotic commented on config/docker.yml
> +    database: 'windbreaker'
windbreaker-badges

2017-09-12 23:39 UTC, Druotic commented on config/localhost.yml
> +    database: 'windbreaker'
windbreaker-badges

2017-09-12 23:39 UTC, Druotic commented on docker-compose.yml
> +      - .:/usr/windbreaker-hooks
hooks?

2017-09-12 23:39 UTC, Druotic commented on docker-compose.yml
> +      - .:/usr/windbreaker-hooks
hooks?

2017-09-12 23:39 UTC, Druotic commented on docker-compose.yml
> +      - /usr/windbreaker-hooks/node_modules
hooks?

2017-09-12 23:39 UTC, Druotic commented on docker-compose.yml
> +      POSTGRES_DB: 'windbreaker'
windbreaker-badges

2017-09-12 23:39 UTC, Druotic commented on package.json
> +    "get-port-sync": "^1.0.0",
Are all of these dependencies used?

2017-09-12 23:39 UTC, Druotic commented on src/startup-tasks/index.js
> +  return tasks
Optional, but `.map` could be used here to simply this a bit.

2017-09-17 15:19 UTC, merged

2017-09-17 19:15 UTC, austinkelleher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Windbreaker Badges Service](https://trello.com/c/72Fie46a/10-windbreaker-badges-service)